lib/bandstock_web/router.ex
defmodule BandstockWeb.Router do
  use BandstockWeb, :router


  pipeline :browser_nouser do
      plug :accepts, ["html"]
      plug :fetch_session
      plug :fetch_flash
      plug :protect_from_forgery
      plug :put_secure_browser_headers
  end

  #pipeline :browser do
  #  plug :accepts, ["html"]
  #  plug :fetch_session
  #  plug :fetch_flash
  #  plug :protect_from_forgery
  #  plug :put_secure_browser_headers
  #  plug BandstockWeb.Plugs.SetUser
  #  #plug BandstockWeb.Plugs.CheckRegistration
  #end

  pipeline :api do
    plug :accepts, ["json"]
  end

  #scope "/handle", BandstockWeb do
    #pipe_through :browser_nouser
    #get "/update_handle", UserController, :update_handle

  #end



  scope "/", BandstockWeb do
    pipe_through :browser_nouser # Use the default browser stack

    get "/", PageController, :index
    get "/about", PageController, :about
    get "/signout", AuthController, :signout
    get "/sold_out", PageController, :about
    get "/red_founder", PageController, :about
    get "/canceled", PageController, :about

    get "/users", UserController, :index
    get "/users/:id", UserController, :show

    get "/boards/new", BoardController, :new
    get "/boards", BoardController, :index
    post "/boards", BoardController, :create
    get "/boards/:id", BoardController, :show
  end

  #resources "/boards", BoardController, except: [:new, :edit]

  scope "/admin", BandstockWeb do
    get "/", UserController, :admin
  end


    #get "/boards", BoardController, :index
#     board_path  GET     /boards/:id               BoardController :show
#     board_path  POST    /boards                   BoardController :create
# board_path  PATCH   /boards/:id               BoardController :update
#             PUT     /boards/:id               BoardController :update
# board_path  DELETE  /boards/:id               BoardController :delete

    #get "/users", UserController, :index
    #get "/users/new", UserController, :new
    #post "/users", UserController, :create
    #get "/users/:id/edit", UserController, :edit
    #get "/users/register", UserController, :register
    #get "/users/:id", UserController, :show
    #delete "/users/:id", UserController, :delete
    #put "/users/:id", UserController, :update


  scope "/board/", BandstockWeb do
    get "/link", BoardController, :link

  end

  scope "/auth", BandstockWeb do
    pipe_through :browser_nouser

    get "/register", AuthController, :register
    get "/:provider", AuthController, :request
    get "/:provider/callback", AuthController, :callback
    post "/:provider/callback", AuthController, :callback
  end

  #scope "/tile", BandstockWeb do
    #pipe_through :browser
    #get "/index", TileController, :index
    #get "/heap", TileController, :heap
  #end

  # Other scopes may use custom stacks.
  # scope "/api", BandstockWeb do
  #   pipe_through :api
  # end
end

lib/bandstock_web/views/layout_view.ex
defmodule BandstockWeb.LayoutView do
  use BandstockWeb, :view
end

lib/bandstock_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Bandstock</title>
    <link href="https://fonts.googleapis.com/css?family=Press+Start+2P|Roboto+Slab" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/css/materialize.min.css">
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Gugi">
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Montserrat">
    <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <link rel="stylesheet" type="text/css" href="<%= static_path(@conn, "/css/app.css") %>">

    <script src="<%= static_path(@conn, "/js/pixi.min.js") %>"></script>
    <script type="<%= static_path(@conn, "/js/config.js") %>"></script>
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
    <script src="<%= static_path(@conn, "/js/materialize.js") %>"></script>
    <script src="<%= static_path(@conn, "/js/init.js") %>"></script>

    <!-- Facebook Pixel Code -->
    <script>
      !function(f,b,e,v,n,t,s)
      {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
      n.callMethod.apply(n,arguments):n.queue.push(arguments)};
      if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
      n.queue=[];t=b.createElement(e);t.async=!0;
      t.src=v;s=b.getElementsByTagName(e)[0];
      s.parentNode.insertBefore(t,s)}(window, document,'script',
      'https://connect.facebook.net/en_US/fbevents.js');
      fbq('init', '266953737394301');
      fbq('track', 'PageView');
    </script>
    <noscript><img height="1" width="1" style="display:none"
      src="https://www.facebook.com/tr?id=266953737394301&ev=PageView&noscript=1"
    /></noscript>
    <!-- End Facebook Pixel Code -->

  </head>

  <body class="black" onload="init()">
    <div class="container">
      <header>
        <div class="row">
          <div class="col s1 pink accent-4 pink-text text-accent-4  center-align">~</div>
          <div class="col s1 purple accent-4 purple-text text-accent-4 center-align">B</div>
          <div class="col s1 indigo accent-4 indigo-text text-accent-4 center-align">A</div>
          <div class="col s1 light-blue light-blue-text accent-4 text-accent-4 center-align">N</div>
          <div class="col s1 cyan cyan-text accent-4 text-accent-4 center-align">D</div>
          <div class="col s1 teal teal-text accent-4 text-accent-4 center-align">S</div>
          <div class="col s1 green green-text accent-4 text-accent-4 center-align">T</div>
          <div class="col s1 lime lime-text accent-4 text-accent-4 center-align">O</div>
          <div class="col s1 yellow yellow-text accent-4 text-accent-4 center-align">C</div>
          <div class="col s1 orange orange-text accent-4 text-accent-4 center-align">K</div>
          <div class="col s1 red red-text accent-4 text-accent-4 center-align">~</div>
          <div class="col s1 pink pink-text accent-4 text-accent-4 center-align">.</div>

          <div class="col s12 black accent-4 right" style="padding-top:10px;">
            <ul class="left">
              <li class="yellow-text text-accent-4" role="alert"><%= get_flash(@conn, :info) %></li>
              <li class="" role="alert"><%= get_flash(@conn, :error) %></li>
            </ul>
            <ul class="right">
              <%= if @conn.assigns[:user] do %>
                <li>
                  <a href="<%= page_path(@conn, :about)%>">
                    <img  src="<%= static_path(@conn, "/images/icons/qmark.png") %>">
                  </a>
                  <%= link "Sign Out", to: auth_path(@conn, :signout), class: "yellow-text text-accent-4" %>
                </li>
              <% else %>
                <li>
                  <!---  --->
                  <span style="padding:5px">
                    <a href="<%= page_path(@conn, :about)%>">
                      <img  src="<%= static_path(@conn, "/images/icons/qmark.png") %>">
                    </a>
                  </span>
                  <span style="padding:5px">
                    <a href="<%= auth_path(@conn, :request, "facebook")%>">
                      <img  src="<%= static_path(@conn, "/images/icons/key1.png") %>">
                    </a>
                </span>
                </li>
              <% end %>
            </ul>
          </div>
          <div>
            		<img style="padding-bottom:75px" width="100%" src="<%= static_path(@conn, "/images/logo2.png") %>">
          </div>
        </div>
      </header>
      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>
    </div> <!-- /container -->
  </body>
</html>